name: Release Notification

on:
  release:
    types: [ published ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Extract release info
        id: release
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "name=${{ github.event.release.name }}" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.release.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Convert release body to Slack format
        id: slackify
        uses: LoveToKnow/slackify-markdown-action@v1.1.1
        with:
          text: "${{ env.body }}"

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "C08CVJVSPQF"
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚀 New Release: ${{ steps.release.outputs.name }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Version:* ${{ steps.release.outputs.tag }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJson(steps.slackify.outputs.text) }}
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.release.html_url }}|View Release on GitHub>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.APP_OAUTH_TOKEN }}
